### ISSUE TITLE
Should Table Transformation be Matrix transformation?

### ISSUE THREAD

**Issue by larrystrickland** [Xalgorithms/xa-arch#1]
Thinking about how you are going to use the Xalgo language, I believe most of the transformations will be matrix transformations.  As a result, it might be worth while exploring whether the terminology should be more aligned with Matrices rather than tables.

**Comment by karfai** [comment]
Can you be more specific about aligning with matrices or matrix terminology? Do you mean using language like "cartesian product" or something like that? I picked words that *sort of* derived from relational algebra (https://en.wikipedia.org/wiki/Relational_algebra) because I see most transformations acting in a row oriented manner. Can you think of a more *matrix algebra* example that illustrates your point?

**Comment by larrystrickland** [comment]
I'll see your url and raise you another (https://en.wikipedia.org/wiki/Matrix_(mathematics))    It all depends on how you are envisaging the rules working.  I can see an invoice being converted to a matrix, that then needs to be multiplied by a vector of taxes.  But if the rules are going to have a more SQL like approach to data manipulation, then Relational-Algebra would work.  

As I said - I'm projecting on how these are going to be used.  So maybe some concrete examples of the table (or matrix) manipulation that needs to be done, would help.

**Comment by jpotvin** [comment]
IoR provides Transformation Matrices
https://www.khanacademy.org/math/precalculus/precalc-matrices/matrices-as-transformations/v/transforming-position-vector

Joseph Potvin
Executive Director, Xalgorithms Foundation
Mobile: 819-593-5983
jpotvin@xalgorithms.org
https://www.xalgorithms.org

**Comment by mcr** [comment]
Larry Strickland <notifications@github.com> wrote:
    > how you are envisaging the rules working. I can see an invoice being
    > converted to a matrix, that then needs to be multiplied by a vector of
    > taxes. But if the rules are going to have a more SQL like approach to
    > data manipulation, then Relational-Algebra would work.

How does the matrix deal with some items needing the tax and others not?
Yes, we can have another vector for that in there, but to be clear, it's a
combination of the properties of the item and the properties of the buyer and
seller that determine things.

**Comment by jpotvin** [comment]
How about Julia (MIT licensed):
https://github.com/JuliaLang
http://docs.julialang.org/en/release-0.4/manual/arrays/
https://github.com/JuliaLang/julia
http://quant-econ.net/jl/julia_arrays.html

Joseph Potvin
Executive Director, Xalgorithms Foundation
Mobile: 819-593-5983
jpotvin@xalgorithms.org
https://www.xalgorithms.org

**Comment by larrystrickland** [comment]
MCR - you make a valid point.  There will be multiple attributes, that I guess will be captured as columns in a table.  Not an obvious parallel in Matrices
